### ISSUE TITLE
MVP Site - Experience Editor doesn't work locally

### ISSUE THREAD

**Issue by robearlam** [Sitecore/XM-Cloud-Introduction#116]
The Experience Editor doesn't work for the MVP site when running in Full Local Development mode.

**Comment by gary1125** [comment]
It is still an issue for me. 
![image](https://user-images.githubusercontent.com/1879390/195006205-d093b458-e905-4b7e-b09b-09e9979f86aa.png)

Before that I got an error "Access to the path 'c:\windows\system32\inetsrv\jss-render' is denied.". I fixed it with a PowerShell script and gave "Everyone" full control of "inetsrv" folder.

Could you take a look again? Thanks.

**Comment by robearlam** [comment]
It looks like you're attempting to open the /Application route, and you wont have an instance of the API for it to connect to which may be causing issues. 

Can you render any of the other pages in EE, or does this happen for every page for the MVP site?

**Comment by gary1125** [comment]
Thanks for the quick response. It happens to every page for the MVP site. BTW, I haven't set up MVP_Selections_API, because I don't know what the endpoint should look like. I don't think it's the issue though.
