### ISSUE TITLE
SUGCON EU - SEO - H1 should be descriptive of the page

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/XM-Cloud-Introduction#135]
The SUGCON EU site (https://sugcon-eu.vercel.app/) uses a very long piece of text for the H1 tag. For SEO purposes, H1 tags should be very descriptive of the content such that people searching for a page will hit that particular page based on the H1 content. 

The current content is likely H2 type of content, and a proper H1 which is more reflective of the site should be used.

NOTE: This may mean changing the code or templates as well to support outputting the 'description' content in a styled way without using the Title field, which should be output for things like browser title and the H1.

**Comment by robearlam** [comment]
This is no longer an issue
