### ISSUE TITLE
PowerShell Reports not available

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/XM-Cloud-Introduction#136]
From the XM Cloud Dashboard, launch the PowerShell Reports application option.

"No report data available.
Is the remoting service enabled?
Are the reporting modules installed and enabled?"

I'm not sure if this is a product issue or a configuration issue.

**Comment by michaellwest** [comment]
This is likely a configuration issue. The reporting feature should be enabled. If however it's not used then probably not worth the trouble of changing anything.

**Comment by jst-cyr** [comment]
We aren't using it right now, so this is definitely lower priority, but I'd like the repo to be in a properly configured state so that people could use the reports if they wanted to, or just demo the reports off this example.
