### ISSUE TITLE
SUGCON Footer Icons - Component

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/XM-Cloud-Introduction#142]
Add social icons to the SUGCON sites footer (twitter, youtube, github etc)

**Comment by sebastiantecsi** [comment]
MVP website has social links displayed in the footer.
Are you talking about EU/ANZ websites?

cc @jst-cyr

**Comment by jst-cyr** [comment]
@sebastiantecsi : You are correct, this was about the SUGCON websites. I doubled checked issue #140 and #141 that I entered on the same day, and they are all issues around SUGCON. Been a while, but I think this issue was created when we transitioned a bunch of internal issues over to GitHub.
