### ISSUE TITLE
MVP Application - Button missing text

### ISSUE THREAD

**Issue by robearlam** [Sitecore/XM-Cloud-Introduction#144]
It looks like there is a button here without any text? I looked at the content item but couldn't see any unpopulated fields?

![image](https://user-images.githubusercontent.com/2149251/193485771-8b2dad31-9aba-4f35-8c4e-4dce8eac6687.png)

**Comment by sc-ivanlieckens** [comment]
Issues with Edge publishing in the Staging environment
