### ISSUE TITLE
Contributions Future Date

### ISSUE THREAD

**Issue by sitecorerunner** [Sitecore/XM-Cloud-Introduction#149]
I was able to select a future date for contributions. Not sure if that is allowed or not.

![image](https://user-images.githubusercontent.com/15183642/194072455-ac81fc70-0986-41d8-aead-9530531be4eb.png)

**Comment by IvanLieckens** [comment]
I see no issues here since it allows already adding speaking engagements in the future. Some asks have been made to make Contributions accessible in a search/dashboard/overview

@mrtamasvarga your call

**Comment by sc-ivanlieckens** [comment]
After meeting with @mrtamasvarga the following was decided: The earliest date will be applications end date - 18 months and the last date accepted for a contribution will be the applications end date itself giving a time window of valid for contribution dates.
