### ISSUE TITLE
MVP Application Description and Link issues

### ISSUE THREAD

**Issue by michaellwest** [Sitecore/XM-Cloud-Introduction#151]
I would recommend that the Description field be much wider and the Link field be shortened with some friendly display text.

**Comment by sc-ivanlieckens** [comment]
I increased the width of the Description in #153 but not sure what you mean by friendly display text on the Link field? You mean like watermark text to show the right format?

**Comment by michaellwest** [comment]
I was thinking a simple solution would be a link tag where the text is just
"Link and the" href is the actual URL. Some of the links could get really
long and provide an inconsistent width on the table.

**Comment by IvanLieckens** [comment]
Ow you were talking about the table and not the form! Ok now I'm with you. I'll enhance it in the next PR.
