### ISSUE TITLE
MVP site - Getting 404 when accessing Application page from Android

### ISSUE THREAD

**Issue by chorpo** [Sitecore/XM-Cloud-Introduction#163]
When trying to access Application page (https://mvp-production.azurewebsites.net/Application) from my Android device (Moto G G5 / Android 11) via Chrome, I am getting 404 Page not found error. Therefore I cannot see login button on top of the page.

![image](https://user-images.githubusercontent.com/517741/194484332-57fca83c-f0bb-4ad0-8eca-3cc227071fad.png)

**Comment by sc-ivanlieckens** [comment]
Confirmed issue, raised with the Sitecore DevEx team under reference nr 555373
