### ISSUE TITLE
init.ps1 file generates unsupported variable values for the docker

### ISSUE THREAD

**Issue by jindrichpiroutek** [Sitecore/XM-Cloud-Introduction#170]
Hello,

I am trying to run the Sitecore XM Cloud locally but quickly ran into the issue with the `TELERIK_ENCRYPTION_KEY` variable, which is generated as a random string. 

In the phase of building docker containers, I got this error message:
`Invalid template: "jo|[Pbj6jdF;!sSY8/j/Bk}RxZFg}>&5_S&/Dn2%?m5)saR1ZbL6+<.17K@.gm$>MsR;TE_%$WS)_^indtx2Zmvz5h:y4}659[M}E:d!D}q~Ojp34*@?4y:$fI)4(5m"`

Turns out I was not lucky, and my generated variable value contained "$", which had to be escaped. So I had to fix this manually. It may be a good idea to avoid this problem when generating these variables for others. 

Ref. here: https://github.com/docker/compose/issues/9704#issuecomment-1202335152

**Comment by robearlam** [comment]
Fixed by #223
