### ISSUE TITLE
Make contributions editable

### ISSUE THREAD

**Issue by monkey-dsc** [Sitecore/XM-Cloud-Introduction#180]
It would be really great if MVP application contributions are editable, instead of deleting them and create them again.

**Comment by agehlot-hi** [comment]
The major feature that is must to have is Update or Edit the line item. Without this, we have to delete the item and reenter the content even for just category change. Thanks for adding that.

**Comment by agehlot-hi** [comment]
Hi @robearlam , while clicking on Edit button, i am getting below error.
![image](https://github.com/Sitecore/XM-Cloud-Introduction/assets/73245956/5d511ee8-d8c5-44e8-809e-70e5b458e883)

**Comment by robearlam** [comment]
@sc-ivanlieckens can you take a look at the error @agehlot-hi is getting?

**Comment by sc-ivanlieckens** [comment]
@robearlam on it, expect a fix in the next hour
