### ISSUE TITLE
All contributions are gone, Application have to be started from the beginning

### ISSUE THREAD

**Issue by monkey-dsc** [Sitecore/XM-Cloud-Introduction#181]
So sad... 3 hours of work on my apllication is gone... :(

Started my application today, I was quite finished with all of my contributions then I got a server error and now I have to start from scratch :(

If I now come to step 3 to choose the category I get one of the following errors:

![image](https://user-images.githubusercontent.com/6951458/199458101-bd8b6afe-2233-48a6-bd12-e5533a300892.png)

![image](https://user-images.githubusercontent.com/6951458/199458247-e5af539a-e974-47ba-b6bb-0f1aa25f32f6.png)

**Comment by monkey-dsc** [comment]
The issue is reproduceable now. Don't use the reload button or even reload the page during adding your contributions, in some cases your token may expire, don't reload the form! Just Log out and Log in again and everthing is fine. At every time you will reload the form the contribution is added twice:

![image](https://user-images.githubusercontent.com/6951458/199630222-b6788279-7ce8-401d-aaf1-e704e2f32724.png)

![image](https://user-images.githubusercontent.com/6951458/199630193-5b0d550d-0b64-455c-b585-792f49c9491e.png)

I started to delete those duplicates yesterday and ended up in an error.

**Comment by monkey-dsc** [comment]
Okay I guess the problem is now obvisously, you can not post more that 25 contributions, otherwise the app will be broken and you have to start from scratch. Hopefully @IvanLieckens can fix that otherwise you have to summarize your contributions as good as you can.

**Comment by sc-ivanlieckens** [comment]
@monkey-dsc there is an infinite loop issue in the serialization between Contribution-Product-Contribution which has been fixed in the API now and should resolve this issue. (Infinite loop causes an OutOfMemory which causes Azure to kill the Functions instance which creates significant delays and other issues when this occurs as all concurrent requests are killed as well)
