### ISSUE TITLE
Sitemap for europe.sugcon.events not working

### ISSUE THREAD

**Issue by sebastiantecsi** [Sitecore/XM-Cloud-Introduction#183]
The Sitemap for europe.sugcon.events not working.
https://europe.sugcon.events/sitemap.xml goes to 404
And [Robots.txt for europe.sugcon.events ](https://europe.sugcon.events/robots.txt)has wrong link to sitemap.xml it points here https://xmc-sitecoresaa94c3-xmcloudintr2ef7-production.sitecorecloud.io/sitemap.xml and it should be adjusted and the links that are rendered there are not good.

**Comment by robearlam** [comment]
Both the robots.txt and sitemap.xml are now reporting the correct URL's for the SUGCON EU site.
