### ISSUE TITLE
Contribution - Provide an option to select date range

### ISSUE THREAD

**Issue by khushboosorthiya** [Sitecore/XM-Cloud-Introduction#194]
I would like to have an option select date range when we add a contribution. We do some of the activities through out the year. For example, Sitecore Mentorship Program, Leading Sitecore User Group, etc. In this scenario, it is too much to add an entry for all the things we do as part of these activities. It would be good to have an option to select a date range in this scenarios or any other alternative.

**Comment by sc-ivanlieckens** [comment]
We have no intention of making the Contribution Date a "range", you can simply place the contribution on the first or last date of the Selection term. @mrtamasvarga to confirm.

**Comment by mrtamasvarga** [comment]
I agree with @sc-ivanlieckens, please select when you started the activity and specify in the description how long did it take.
