### ISSUE TITLE
Link to go back to Dashboard

### ISSUE THREAD

**Issue by khushboosorthiya** [Sitecore/XM-Cloud-Introduction#195]
https://mvp.sitecore.com/Application
We have two options on the Dashboard page - My Data and My Current Application.

But there is no option to go back to dashboard from both of these pages:
https://mvp.sitecore.com/Application/My-Data
https://mvp.sitecore.com/Application/Apply

It would be easy if there is a back button to navigate to Dashboard page.

**Comment by robearlam** [comment]
You can just use the Application link from the main menu to return to the Dashboard, so I don't think we need return links on the other pages.
