### ISSUE TITLE
Issue Templates

### ISSUE THREAD

**Issue by sebastiantecsi** [Sitecore/XM-Cloud-Introduction#196]
The **issue templates** are setup here https://github.com/Sitecore/XM-Cloud-Introduction/tree/main/.github/issue_template but look that clicking to **New Issue** https://github.com/Sitecore/XM-Cloud-Introduction/issues does not show you the 2 options.

I guess some adjustments are needed to have things working properly.

**Comment by robearlam** [comment]
This issue has been fixed and Issue Templates are now being used.
