### ISSUE TITLE
I wish to build a function similar to or rectify existing Get-SitecoreRandomString function so that it disallows $ in the generated string

### ISSUE THREAD

**Issue by navancommits** [Sitecore/XM-Cloud-Introduction#224]
wish to know the code base to add such a function, more than happy to do since issue due to $ in random string is common across all Sitecore Docker projects....

**Comment by navancommits** [comment]
Example: https://navansitecorenotes.blogspot.com/2023/01/random-string-generation-powershell.html

**Comment by robearlam** [comment]
That functionality is defined in the Sitecore Docker Tools Repository, so any changes would need to be made there: https://github.com/Sitecore/docker-tools/

Closing this issue as it doesn't relate to this repository.
