### ISSUE TITLE
MVP Search does not consider the multiple Filters

### ISSUE THREAD

**Issue by darjimaulik** [Sitecore/XM-Cloud-Introduction#232]
I want to search the Technology MVPs for 2023. When I select these 2 filters, I still see some of the MVPs who are no longer in Technology MVP for 2023. They were technology MVPs in the Past but not for 2023. 
They should not appear in the search results. 

Select Technology filter
Select 2023 year. Check some MVPs from Strategy and Ambassador category appearing in results.  

Only Technology MVPs for 2023 should appear in the search. 

Check the link at https://mvp.sitecore.com/Directory?q=&fc_Type=Technology&fc_Year=2023

**Comment by robearlam** [comment]
Ok, so the logic in the listing is wrong. Currently when you select both Year & Type, it checkes whether any award matches year and whether any award matches type. So in your example, someone with 2022 Tech & 2023 Ambassador would match, even though that's not really what you want.

We need to change the logic to check whether any awards match both of those options when selected.
