### ISSUE TITLE
Change repo to use Edge CLI Plugin to generate Tokens

### ISSUE THREAD

**Issue by robearlam** [Sitecore/XM-Cloud-Introduction#271]
Currently the `New-EdgeToken.ps1` requires the repo to have been run to configure the CLI, which doesn't make sense.

Since creating the repo there is now a new Edge plugin for the CLI used to generate Edge Tokens, we should change the script above to use this method instead of how it does it currently

**Comment by navancommits** [comment]
Can you please confirm if option 2 or 3 is in mind? 
![image](https://github.com/Sitecore/XM-Cloud-Introduction/assets/55013802/988f9466-e6a0-447a-aa12-3ed24c281e97)

**Comment by robearlam** [comment]
This was investigated already and is no longer required, forgot to close off the issue, so will do now.
