### ISSUE TITLE
Make 404 page on MVP site content managed

### ISSUE THREAD

**Issue by robearlam** [Sitecore/XM-Cloud-Introduction#291]
The 404 page for the MVP site has a content item, but it hasn't been wired up and it's currently serving a static page.

This needs to be connected so that the 404 page content can be managed via XMC.

**Comment by navancommits** [comment]
Any reason why was this left out from current site? If this still fine, I can move over to the current site... https://github.com/navancommits/MVP-Site/commit/32a0739cabe3adc52c7e0f4107caa9fe5d6bf9e4#diff-152ed196c2d58c336f6154f93fdabbdc06005f1adefac2db78e184ea2ddc856b

**Comment by robearlam** [comment]
That change won't work now as we're running against Edge. We need to handle the request in the head application and send retrieve the data when needed, as done with the SUGCON sites.

**Comment by robearlam** [comment]
Closed by #307
