### ISSUE TITLE
Sitecore MVP Application > Multiline text box not showing line space

### ISSUE THREAD

**Issue by AmitKumar-AK** [Sitecore/XM-Cloud-Introduction#296]
**Describe the bug**
If applicant entering the details in the **Why do you believe you are eligible to be selected to be a Sitecore MVP?** multiline text box and submit the application then its not showing the line spaces to applicant after the submit.

**To Reproduce**
Submit the details and preview the submitted application from **applicant view**.

**Expected behavior**
It should show the line spaces to the applicant after submission.

**Comment by sc-ivanlieckens** [comment]
This field supports Markdown since #294 , for Linebreaks: https://www.markdownguide.org/basic-syntax/#line-breaks
