### ISSUE TITLE
Remove appsettings.Development.json from repo

### ISSUE THREAD

**Issue by navancommits** [Sitecore/XM-Cloud-Introduction#308]
**Describe the bug**
Currently appsettings.Development.json gets checked-in even if I add it to .gitignore list. So, good to remove it completely from repo and add it to .gitignore list too

**To Reproduce**
1. Go to C:\projects\tst\XM-Cloud-Introduction\src\Project\MvpSite\rendering\appsettings.Development.json
2. It has your personal OKTA server details 
3. The personal information gets added to git during commit/push

**Expected behavior**
appsettings.Development.json shouldn't be added to git commit list

**Desktop (please complete the following information):**
All OS versions

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by navancommits** [comment]
Will wait for approval before doing anything about this issue....

**Comment by sc-ivanlieckens** [comment]
@navancommits why are you using the file? I've developed for this repo for a long time and I have never touched this file. It's an example of the configuration. In containers the Environment Settings take precedence. Are you running local instead of in containers?

**Comment by robearlam** [comment]
Agree with @sc-ivanlieckens here, I dont see an issue with including the file here as an example.
