### ISSUE TITLE
Sitecore MVP Directory not showing default profile pic for some cards

### ISSUE THREAD

**Issue by gauravpansari1991** [Sitecore/XM-Cloud-Introduction#347]
**Describe the bug**

**To Reproduce**
Go to 'https://mvp.sitecore.com/Directory'
Search for 'James'
It will show some cards a Profile pic but show 1 card with a broken image

Expected behavior
It should show a card with at least default profile pic

**Screenshots**
<img width="504" alt="image" src="https://github.com/Sitecore/XM-Cloud-Introduction/assets/12952868/dc17348e-7782-4b8f-921d-24785a9dd677">

**Comment by sc-ivanlieckens** [comment]
@gauravpansari1991 I'm not sure what happened there but I can't reproduce this?

**Comment by gauravpansari1991** [comment]
@sc-ivanlieckens yeah it's not reproducible now, we can close this ticket and reopen if we find this again.
