### ISSUE TITLE
Sitecore MVP directory not showing Profile Image

### ISSUE THREAD

**Issue by yogeshwersharma1990** [Sitecore/XM-Cloud-Introduction#348]
Describe the bug
Sitecore MVP directory not showing profile image

To Reproduce
Go to 'https://mvp.sitecore.com/Directory'
Search for 'yogeshwer' and it will show up card without profile image.

Expected behavior
I think it should show profile image.

Screenshots
![image](https://github.com/Sitecore/XM-Cloud-Introduction/assets/35720339/86c5f475-d5ae-488f-a661-c37712833ce3)

**Comment by sc-ivanlieckens** [comment]
@yogeshwersharma1990 the directory is showing your profile picture that's been set to use "Twitter". You can adjust this yourself at [My Data](https://mvp.sitecore.com/en/Application/My-Data). I recommend using Gravatar currently as Twitter and the Community have proven to be unstable. I will take a look at them again in light of this issue.

**Comment by yogeshwersharma1990** [comment]
@sc-ivanlieckens  - Thanks I can see image now.
