### ISSUE TITLE
User with duplicate API records

### ISSUE THREAD

**Issue by robearlam** [Sitecore/XM-Cloud-Introduction#354]
It lookslike Adam Wolfd has different API records, for his different award years?

![image](https://github.com/Sitecore/XM-Cloud-Introduction/assets/2149251/6f038a62-21b0-4576-acfa-438224d5b4d2)

**Comment by sc-ivanlieckens** [comment]
@robearlam almost all long-term MVPs have multiple records. Currently the Directory is merging them by name (case sensitive). We have merge capability in the API to solve these. I need to add this to the UI so it's easily accessible to admins.

I'll add a separate item for that and close this one (I executed the merge)
