### ISSUE TITLE
Wrong country assigned to older MVPs

### ISSUE THREAD

**Issue by sebastiantecsi** [Sitecore/XM-Cloud-Introduction#360]
As I was looking on the website https://mvp.sitecore.com/Directory to see the new MVPs of 2024, I have noticed a bunch of people that have the wrong country assigned to them. 

I'll just give you few of them:
* Alina Fodor
* Adrian Iorgu
* Daniel Mocan
* Cristian Vuturar

And many many more.
Is it the recent code updates? And data move to other systems?

PS: By default, everyone's images was puled from Gravatar and looks that not anymore. Maybe you should revert that part.

**Comment by sc-ivanlieckens** [comment]
I'm closing this issue, most profiles have been corrected and many doubles have been merged. If any other out of place data is found feel free to open this issue again and/or contact through email or slack with the profiles that need correcting.
