### ISSUE TITLE
Searching in search box not keeping facet filters

### ISSUE THREAD

**Issue by gauravpansari1991** [Sitecore/XM-Cloud-Introduction#368]
I am not sure if this is a bug or if it should be a feature request, so adding it as a bug, please tell me if this is a valid bug/feature request.

**Describe the bug**
I have the 2018 facet checkbox checked, then if I search like 'gaurav' in the search box, the facet selection is not maintained, it is showing results only for the search box value, 2018 facet is not selected anymore.

**To Reproduce**
1. Go to https://mvp.sitecore.com/Directory
2. Click on Year Facet like '2018', it will show some results
3. Then search for 'gaurav' in the search box
4. Result is showing for 'Gaurav', 2018 facet is not checked anymore

**Expected behavior**
Selected facets should maintained and the result should be an AND operation between facet and search box value

**Screenshots**
1) facet 2018 selection 
<img width="361" alt="image" src="https://github.com/Sitecore/XM-Cloud-Introduction/assets/12952868/a4c0d7f7-083a-4cda-aaf4-43aeb64c6b5a">

2) searching Gaurav in the search box while facet is still selected
<img width="368" alt="image" src="https://github.com/Sitecore/XM-Cloud-Introduction/assets/12952868/fcbb197e-fa33-4933-8611-2a7addf9e9bb">

3) Facet selection is gone - 

<img width="955" alt="image" src="https://github.com/Sitecore/XM-Cloud-Introduction/assets/12952868/3b89d860-a417-40e9-b4a0-df9fcb396c82">

**Comment by sc-ivanlieckens** [comment]
This will be fixed with the implementation of #358

**Comment by robearlam** [comment]
Closed by #420
