### ISSUE TITLE
Countdown Showing Before the Expected Date

### ISSUE THREAD

**Issue by alvaropmontenegro** [Sitecore/XM-Cloud-Introduction#380]
**Describe the bug**
The Countdown is showing on the Application page saying that the Application is open and the amount of time left, such as:

`Applications are currently open! Deadline: 276d 7h 35m 15s`

**To Reproduce**
1. Go to '[Application Page](https://mvp.sitecore.com/Application)'

**Expected behavior**
Show the Countdown only in November when the Application opens.

**Screenshots**
![image](https://github.com/Sitecore/XM-Cloud-Introduction/assets/70984890/c433ccbe-e21f-41fa-aa15-240b29aa9419)

**Comment by robearlam** [comment]
The applications are now open for the full year. This is intentional to allow people to log their contributions throughout the year, as they make them. 

This was done to remove to the load on applicants having to complete the full application in a short timeframe.
