### ISSUE TITLE
Filters are not working correctly or Search is not correct

### ISSUE THREAD

**Issue by gauravpansari1991** [Sitecore/XM-Cloud-Introduction#389]
**Describe the bug**
I selected the "2024" filter and then the "United Arab Emirates" filter, and in number it is showing 13 but actually, it is showing 10 cards in the results. So either the Filters are not showing the correct number or the search is not showing the correct number of cards.

**To Reproduce**
1. Go to 'https://mvp.sitecore.com/Directory'
2. Click on the 'Year' filter, select '2024'
3. Then select 'United Arab Emirates', filter shows 13

<img width="225" alt="image" src="https://github.com/Sitecore/XM-Cloud-Introduction/assets/12952868/6dbd26ce-581b-461b-9a75-7d74486129ce">

5. But the search result is showing 10 cards
<img width="200" alt="image" src="https://github.com/Sitecore/XM-Cloud-Introduction/assets/12952868/41ba8199-ddb1-4130-87a9-bdb346e34cfe">

**Expected behavior**
Either filter should show 10 or the search result should have 13 cards.

**Comment by robearlam** [comment]
The current filter count implementaion isn't linked. There are 13 UAE recipients over all of the years the MVP program has been running. Removing the Year filter will allow you to view all 13.

We are currently rebuilding the directory functionality, and this will be fixed when that is released.
