### ISSUE TITLE
SUGCON24 EU: Agenda and Sessions rendering can not be added in Experience Editor

### ISSUE THREAD

**Issue by gkLeo** [Sitecore/XM-Cloud-Introduction#457]
**Describe the bug**
When adding the Agenda or Sessions in the Experience Editor, an error will occur. A PR is created for this issue #451 

**To Reproduce**
1. Go to Content Editor
2. Right-click on '/sitecore/content/Sugcon2024/EU/Home'
3. Click 'Experience Editor'
4. Click 'Add here' in 'Main' placeholder
5. Click 'EVENTS', then select 'Agenda' or 'Sessions', click 'Select'
6. See error

**Expected behavior**
'Select the Associated Content' dialog box should appear.

**Screenshots**
![image](https://github.com/Sitecore/XM-Cloud-Introduction/assets/20036944/ce182bfb-8812-4db8-b39f-29639c76bc4a)

**Comment by robearlam** [comment]
With this being an XM-Cloud based implementation, we're not targeting Experience Editor support. Efforts will be made for Pages support moving forwards
